import {
  Home,
  ShoppingCart,
  Package,
  Users,
  Building2,
  BarChart2,
  Info,
  Shield,
  Settings,
  LayoutDashboard,
  Pill,
  Hospital,
  GitCompareArrows
} from 'lucide-react';

export const combinedNavItems = [
  { href: '/dashboard', icon: Home, label: 'Visão Geral (Coord.)' },
  { isSeparator: true, label: "CAF" },
  { href: '/dashboard/orders', icon: ShoppingCart, label: 'Pedidos (CAF)' },
  { href: '/dashboard/inventory?location=CAF', icon: Package, label: 'Inventário (CAF)' },
  { href: '/dashboard/patients', icon: Users, label: 'Pacientes (CAF)' },
  { href: '/dashboard/units', icon: Building2, label: 'Unidades' },
  { href: '/dashboard/reports', icon: BarChart2, label: 'Relatórios (CAF)' },
  { isSeparator: true, label: "Hospital" },
  { href: '/dashboard/hospital', icon: LayoutDashboard, label: 'Dashboard (Hospital)' },
  { href: '/dashboard/inventory?location=Hospital', icon: Package, label: 'Inventário (Hospital)' },
  { href: '/dashboard/hospital/dispense', icon: Pill, label: 'Dispensar (Setor)' },
  { href: '/dashboard/hospital/patients', icon: Hospital, label: 'Pacientes Internados' },
  { href: '/dashboard/hospital/reports', icon: BarChart2, label: 'Relatórios (Hospital)' },
  { isSeparator: true, label: "Geral" },
  { href: '/dashboard/inventory', icon: Package, label: 'Inventário (Global)' },
  { href: '/dashboard/user-management', icon: Shield, label: 'Usuários', adminOnly: true },
  { href: '/dashboard/settings', icon: Settings, label: 'Configurações' },
  { href: '/dashboard/about', icon: Info, label: 'Sobre' },
];
